pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'Pages'
urlpatterns = [
    url(r'^$', views.index, name='index')
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'Polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.details, name='details'),
    url(r'^(?P<question_id>\d+)/results.', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote.', views.vote, name='vote'),
]

pollster/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pages.urls', namespace='pages')),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace='polls')),
]

pages/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=now)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
# from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

polls/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from .models import Question, Choice

# Get Questions and display then
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'title': 'Poll Questions', 'latest_question_list': latest_question_list }
    return render(request, 'polls/index.html', context)

# Show specific question and choices
def details(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        context = { 'title': 'Choose your favorite', 'question': question }
    except Question.DoesNotExistList:
        raise Http404("Question does not exists")

    return render(request, 'polls/detail.html', context)

# Get question and display results

def results(request, question_id):
    # return HttpResponse("Results")

    try:
        question = get_object_or_404(Question, pk=question_id)
        context = { 'title': 'Results so far...', 'question': question }
    except Question.DoesNotExistList:
        raise Http404("Question does not exists")

    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pollster | {{title}} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/cfc6ed36db.js" crossorigin="anonymous"></script>
</head>
<body>
    {%include 'partials/_navbar.html'%}
    <div class="section" style="padding-bottom: 0.5rem;">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-half-desktop is-two-thirds-tablet">
                    {%block content%}{%endblock%}
                </div>
            </div>
            <hr/>
        </div>
    </div>
    <!-- {% debug %} -->
</body>
</html>

templates/pages/index.html
{%extends 'layout.html'%}

{%block content%}
<h2 class="title is-2 has-text-centered">Welcome to Pollster</h2>
<div class="card has-text-centered">
    <div class="card-content">
        <p class="">This is an example Django Polling app</p>
        <div class="clearfix">&nbsp;</div>
        <a href="{% url 'polls:index'%}" class="button is-link is-fullwidth">View available Polls</a>
    </div>
</div>
{%endblock%}

templates/partials/_navbar.html
<nav class="navbar is-dark is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <!-- <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: Free, open source, and modern CSS framework based on Flexbox" width="112" height="28" /> -->
            <div class="is-size-4 is-light">Polster</div>
        </a>
        <a href="/admin" class="navbar-item is-pulled-right">
            Admin
          </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="true">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div class="navbar-menu">
        <div class="navbar-end">
          <a href="/admin" class="navbar-item">
            Admin
          </a>
        </div>
    </div>
</nav>
<div class="clearfix">&nbsp;</div>

templates/polls/detail.html
{%extends 'layout.html'%}

{%block content%}
<style>.buttons .button { flex: 1; text-align: center;} .buttons .button:last-child { flex: 3; margin-left: 0.5rem; }</style>
<h2 class="title is-2 has-text-centered">{{ title }}</h2>
<h4 class="title is-4">{{ question.question_text }}</h4>
{% if error_message %}
<p class="notification is-danger is-small"><button class="delete" onclick="this.parentNode.classList.add('is-hidden');"></button><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="/polls/{{question.id}}/vote/" method="post">
    {% csrf_token %}
    <ul class="list control">
        {% for choice in question.choice_set.all %}
        <li class="list-item is-5">
            <label class="radio" for="choice{{ forloop.counter }}">
                <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
                {{ choice.choice_text }}
            </label>
        </li>
        {% endfor %}
    </ul>
    <div class="subtitle buttons">
        <a class="button is-link is-outlined" href="/polls">
            <i class="fas fa-chevron-left"></i>
            <i class="fas fa-chevron-left" style="margin-left: -3px !important;"></i>
            &nbsp;Back to Polls</a>
        <input type="submit" value="Vote" class="button is-link">
    </div>
</form>
{%endblock%}

templates/polls/index.html
{%extends 'layout.html'%}

{%block content%}
<style>.buttons .button { flex: 1;} .buttons .button:first-child { flex: 3;}</style>
<h2 class="title is-2 has-text-centered">{{ title }}</h2>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card">
        <div class="card-content">
          <h4 class="title is-4">{{ question.question_text }}</h4>
          <div class="title buttons">
            <a href="/polls/{{ question.id }}" class="button is-link">Vote Now</a>
            <a href="/polls/{{ question.id }}/results" class="button is-link is-outlined">Results</a>
          </div>

        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{%endblock%}

templates/polls/results.html
{% extends 'layout.html' %}

{% block content %}
<style>.buttons .button { flex: 1;} .buttons .button:first-child { flex: 3;}</style>
<h2 class="title is-2 has-text-centered">{{ title }}</h2>
<h4 class="title is-4 has-text-center">{{ question.question_text }}</h4>
<ul class="list">
    {% for choice in question.choice_set.all %}
    <li class="list-item is-5">
        {{ choice.choice_text }}&nbsp;<span
            class="tag is-link is-pulled-right">{{ choice.votes }}&nbsp;vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
<div class="buttons">
    <a class="button is-link" href="/polls">
        <i class="fas fa-chevron-left"></i>
        <i class="fas fa-chevron-left" style="margin-left: -3px !important;"></i>
        &nbsp;Back to Polls</a>
    <a class="button is-link is-outlined" href="/polls/{{ question.id }}">Vote again ?</a>
</div>
{% endblock %}subtitle